language: php

dist: trusty

php:
  - '7.3'

env:
  - DOCKER_COMPOSE_VERSION=1.24.1
  - DATABASE_URL=mysql://root:XXXX@db:3306/project
#  - CODECOV_TOKEN="" ## Not required on Travis-CI [...] for public repositories.

services:
  - docker
  - mysql

before_install:
  - sudo service mysql stop
  - make docker-start
  - sleep 15

install:
  - make composer
  - make yarn

script:
  - make travis

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

#after_failure:
#  - TODO

#branches:
#  only:
#    - master

#sudo: required

#dist: trusty

#cache:
#  directories:
#    - "vendor"
#    - "node_modules"