version: '3'

services:
  server:
    container_name: ${APP_URL}-server
    build: ./docker/php-apache
    ports:
      - ${APACHE_PORT}:80
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./server:/var/www/html
      - ./docker/php-apache/logs:/var/log/apache2
      - ./docker/php-apache/vhosts/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - project_default

  client:
    container_name: ${APP_URL}-client
    build: ./docker/nodejs
    ports:
      - ${NODE_SERVER_PORT}:3000
    volumes:
      - ./client:/usr/src/app
    networks:
      - project_default
    stdin_open: true
  
  db:
    container_name: ${APP_URL}-mysql
    image: mysql:latest
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: majority
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
    command: 
      # - mysqld --sql_mode=""
      - --default-authentication-plugin=mysql_native_password
    networks:
      - project_default

  adminer:
    container_name: ${APP_URL}-adminer
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    links:
      - db
 
volumes:
  src:
    driver: local
  db:
    driver: local
  
networks:
  project_default:
